config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'events#index'
  resources :involvements, only: [:create, :destroy]
  resources :events do
    collection do
      get :your
    end
  end

  # resources :involvements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :time, presence: true
  validates :date, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :involvements
  has_many :attendees, through: :involvements, source: :attendee
  scope :past, -> { where("date < ?", Date.today) }
  scope :coming, -> { where("date >= ?", Date.today) }
end

app/models/involvement.rb
class Involvement < ApplicationRecord
  validates :attendee_id, uniqueness: { scope: :event_id }
  belongs_to :attendee, class_name: 'User'
  belongs_to :event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: 'creator', class_name: 'Event', dependent: :destroy
  has_many :involvements, foreign_key: 'attendee_id', class_name: 'Involvement'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, except: [:index]

  def index
    @events = Event.all
    @past = Event.past
    @coming = Event.coming
  end

  def show
    @event = Event.find(params[:id])
  end

  def your
    @events = Event.all
  end

  def new
    @event = current_user.events.new
  end

  def create
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to @event
      flash[:success] = 'Great! Your event has been created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to your_events_path, status: :see_other
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :date, :time)
  end

  def require_login
    unless current_user
      flash[:error] = 'You must be logged in first.'
      redirect_to new_user_session_path
    end
  end
end

app/controllers/involvements_controller.rb
class InvolvementsController < ApplicationController
  before_action :authenticate_user!
  def create
    # @involvement = current_user.involvements.build(involvement_params)
    @involvement = Involvement.new(involvement_params)

    if @involvement.save
      @event = Event.find(@involvement.event_id)
      flash[:notice] = "You are now joining to the #{@event.title} event."
      redirect_to your_events_path
    end
  end

  def destroy
    @involvement = Involvement.find(params[:id])
    @involvement.destroy

    @event = Event.find(@involvement.event_id)
    flash[:alert] = "You are no longer joining to the #{@event.title} event."
    redirect_to your_events_path
  end

  private

  def involvement_params
    params.require(:involvement).permit(:attendee_id, :event_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # after_action :after_sign_in, :only => :create
  # def after_sign_in
  #    flash[:message_of_the_day] = "Welcome to our site!"
  # end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  #   flash[:success] = "Welcome to Private Events!"
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    flash[:see_you] = 'See you!'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/involvements_helper.rb
module InvolvementsHelper
end

app/views/events/_form.html.erb
<div class="container"></br></br>
  <div class="row">
    <div class="col-1 col-lg-4">
    </div>
    <div class="col-10 col-lg-4">
      <% if @event.errors.any? %>
      <div id="error_explanation">
          <h2 class="text-danger" ><%= pluralize(event.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
          <% @event.errors.full_messages.each do |msg| %>
          <li class="text-secondary"><%= msg %></li>
          <% end %>
          </ul>
      </div>
      <% end %>
      <div class="card shadow p-3 mb-5 bg-body rounded">
        <div class="card-body">
          <%= form_with model: event do |form| %>
            <div class="mb-3">
              <%= form.label :title %><br>
              <%= form.text_field :title, class: 'form-control' %>
            </div>

            <div class="mb-3">
              <%= form.label :description %><br>
              <%= form.text_area :description, class: 'form-control' %>
            </div>

            <div class="mb-3">
              <%= form.label :location %><br>
              <%= form.text_field :location, class: 'form-control' %>
            </div>

            <div class="mb-3">
              <%= form.label :date %><br>
              <%= form.date_select :date, class: 'form-control' %>
            </div>

            <div class="mb-3">
              <%= form.label :time %><br>
              <%= form.time_select :time %>
              <%# <%= form.time_zone_select :timezone %>
            </div>

            <div class="mb-3">
              <%= form.submit %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-1 col-lg-4">
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-1 col-lg-4">
    </div>
    <div class="col-10 col-lg-4"></br>
        <h1>Edit Event</h1>
    </div>
    <div class="col-1 col-lg-4">
    </div>
  </div>
</div>
<%= render "form", event: @event %>

app/views/events/index.html.erb
<div class="container"></br>
<h3 class="d-flex justify-content-center">All Events</h3></br>
  <h5>Upcoming Events:</h5></br>
  <div class="row">
    <% @coming.each do |event| %>
    <div class="col-12 col-lg-4 d-flex justify-content-center"></br>
        <div class="card shadow p-3 mb-5 bg-body rounded" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= event.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= event.location %></h6>
            <p class="card-subtitle mb-2 text-muted"><%= event.time.strftime("%k:%M") %> | <%= event.date.strftime("%d/%m/%Y") %></p>
            <a href="#" class="card-link"><%= link_to 'Show', event_path(event.id) %></a>
          </div>
        </div>
      </div>
    <% end %>
  </div></br></br>
  <h5>Passed Events:</h5></br>
  <div class="row">
    <% @past.each do |event| %>
    <div class="col-12 col-lg-4 d-flex justify-content-center"></br>
        <div class="card shadow p-3 mb-5 bg-body rounded" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= event.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= event.location %></h6>
            <p class="card-subtitle mb-2 text-muted"><%= event.time.strftime("%k:%M") %> | <%= event.date.strftime("%d/%m/%Y") %></p>
            <a href="#" class="card-link"><%= link_to 'Show', event_path(event.id) %></a>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-1 col-lg-4">
    </div>
    <div class="col-10 col-lg-4"></br>
        <h1>New Event</h1>
    </div>
    <div class="col-1 col-lg-4">
    </div>
  </div>
</div>
<%= render "form", event: @event %>

app/views/events/show.html.erb
</br>
<div class="card">
  <h5 class="card-header"><%= @event.title %></h5>
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted"><%= @event.creator.email %></h6>
    <h6 class="card-subtitle mb-2 text-muted"><%= @event.location %>, <%= @event.time.strftime("%k:%M") %> | <%= @event.date.strftime("%d/%m/%Y") %></h6>
    <p class="card-text"><%= @event.description %></p>
    <div class="btn-group" role="group" aria-label="Basic example">
      <% if @event.creator == current_user %>
        <%= link_to 'Edit', edit_event_path(@event.id), class: 'btn btn-link p-0' %>
        <%= button_to 'Delete', @event, method: :delete, class: 'btn btn-link p-0 mx-3'%>
      <% elsif @event.attendees.include?(current_user) %>
        <% @involvement = current_user.involvements.where(event_id: @event.id) %>
        <%= button_to 'Not Join', involvement_path(@involvement.ids), :method => 'delete', class: 'btn btn-link p-0' %>
      <% else %>
        <%= button_to 'Join Event', involvements_path(@event), params: { involvement: { event_id: @event.id, attendee_id: current_user.id } }, class: 'btn btn-link p-0' %>
      <% end %>
        <%= link_to 'All Events', events_path, data: { turbo_action: "replace" }, class: 'btn btn-link p-0 mx-3' %>
    </div>
  </div>
</div>
</br>
<div class="card">
  <div class="card-header">
    Attendees
  </div>
  <ul class="list-group list-group-flush">
      <% @event.attendees.each do |attendee| %>
        <li class="list-group-item" >
          <%= attendee.email %>
        </li>
      <% end %>
  </ul>
</div>

app/views/events/your.html.erb
<div class="container d-flex justify-content-center">
  <div class="row container-md d-flex justify-content-center">
    <div class="col container-md"></br>
      <h5>Events You Created:</h5></br>
      <% current_user.events.each do |event| %>
        <div class="card shadow p-3 mb-5 bg-body rounded" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= event.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= event.location %></h6>
            <p class="card-subtitle mb-2 text-muted"><%= event.time.strftime("%k:%M") %> | <%= event.date.strftime("%d/%m/%Y") %></p>
            <%# <p class="card-text"></p> %>
            <a href="#" class="card-link"><%= link_to 'Show', event_path(event.id) %></a>
          </div>
        </div></br>
      <% end %>
    </div>
    <div class="col container-md "></br>
        <h5>Joined Upcoming Events:</h5></br>
        <% current_user.involvements.each do |involvement| %>
          <% @event = Event.find(involvement.event_id) %>
          <% if @event.date >= Date.today %>
          <div class="card shadow p-3 mb-5 bg-body rounded" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"><%= @event.title %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= @event.location %></h6>
              <p class="card-subtitle mb-2 text-muted"><%= @event.time.strftime("%k:%M") %> | <%= @event.date.strftime("%d/%m/%Y") %></p>
              <div class="btn-group" role="group" aria-label="Basic example">
                <%= link_to 'Show', event_path(@event.id), class: 'btn btn-link p-0' %>
                <%= button_to 'Not Join', involvement_path(involvement), :method => 'delete', class: 'btn btn-link p-0 mx-3' %>
              </div>
            </div>
          </div></br>
            <% end %>
        <% end %>
    </div>
    <div class="col container-md"></br>
      <h5>Passed Joined Events:</h5></br>
      <% current_user.involvements.each do |involvement| %>
        <% @event = Event.find(involvement.event_id) %>
        <% if Date.today > @event.date %>
        <div class="card shadow p-3 mb-5 bg-body rounded" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= @event.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= @event.location %></h6>
            <p class="card-subtitle mb-2 text-muted"><%= @event.time.strftime("%k:%M") %> | <%= @event.date.strftime("%d/%m/%Y") %></p>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= link_to 'Show', event_path(@event.id), class: 'btn btn-link p-0' %>
              <%= button_to 'Not Join', involvement_path(involvement), :method => 'delete', class: 'btn btn-link p-0 mx-3' %>
            </div>
          </div>
        </div></br>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="app/assets/stylesheets/application.css">
  </head>

  <body class="maincont">

    <%= render 'layouts/home/header'%>
    <%= render 'layouts/flash/notif' %>
    
   <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/flash/_notif.html.erb
<% flash.each do |type, msg| %>
  <div class= "container text-primary">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light navcolor">
  <div class="container-fluid container">
    <%= link_to 'Private Events', events_path, class:"navbar-brand active fs-4 fw-bold mb-0" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <%= link_to 'Create Event', new_event_path, class:"nav-link active" %>
            </li>          
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Your Events', your_events_path, class:"nav-link active" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Profile', edit_user_registration_path, class:"nav-link active" %>
            </li>    
            <li class="nav-item">
                <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link active", class:"btn btn-outline-dark" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class:"nav-link active" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link active" %>
            </li>
        <% end %>      
      </ul>
    </div>
  </div>
</nav>